import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ReduxProvider } from "@/lib/redux/provider";
import { LoadingProvider } from "@/context/LoadingContex";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  display: "optional", // this avoids blocking render if fonts fail to 

});


export const metadata: Metadata = {
  title: "Usha Girls PG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body className="font-montserrat antialiased">
         <LoadingProvider>
              <ReduxProvider>{children}</ReduxProvider>
         </LoadingProvider>
       
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
